// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcSqHhbyQ-34K58Gq0UgC2lCviALOM2E',
    appId: '1:823568799128:web:40cac597171658eb8b47ed',
    messagingSenderId: '823568799128',
    projectId: 'wordgamevnvnvn',
    authDomain: 'wordgamevnvnvn.firebaseapp.com',
    storageBucket: 'wordgamevnvnvn.firebasestorage.app',
    measurementId: 'G-4JJBKW4XPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNG7f0zEzaK8RZVkQNR1t2c0QIrHZfwo0',
    appId: '1:823568799128:android:1dd9a13cb808283b8b47ed',
    messagingSenderId: '823568799128',
    projectId: 'wordgamevnvnvn',
    storageBucket: 'wordgamevnvnvn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmFUEm924aE5zQSXqdzJaJySyd4dkt1CM',
    appId: '1:823568799128:ios:bf81b8c16aa828208b47ed',
    messagingSenderId: '823568799128',
    projectId: 'wordgamevnvnvn',
    storageBucket: 'wordgamevnvnvn.firebasestorage.app',
    iosBundleId: 'com.example.myWordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmFUEm924aE5zQSXqdzJaJySyd4dkt1CM',
    appId: '1:823568799128:ios:bf81b8c16aa828208b47ed',
    messagingSenderId: '823568799128',
    projectId: 'wordgamevnvnvn',
    storageBucket: 'wordgamevnvnvn.firebasestorage.app',
    iosBundleId: 'com.example.myWordGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRcSqHhbyQ-34K58Gq0UgC2lCviALOM2E',
    appId: '1:823568799128:web:cc9aa270dfc951a88b47ed',
    messagingSenderId: '823568799128',
    projectId: 'wordgamevnvnvn',
    authDomain: 'wordgamevnvnvn.firebaseapp.com',
    storageBucket: 'wordgamevnvnvn.firebasestorage.app',
    measurementId: 'G-9C5P5322TN',
  );
}
